a = input('Digite algo: ')
print('O tipo primitivo desse valor é: ', type(a))
print('Só tem espaços?', a.isspace())
print('É numérico?', a.isnumeric())
print('É alfabético?', a.isalpha())
print('É alfanumérico?', a.isalnum())
print('É minúscula?', a.islower())
print('É maiúscula:', a.isupper())
print('É capitalizada?', a.istitle())
